# docker compose.yml
version: "3.9"

services:    
  dev:
    image: signalhouse/dev-ml:11.4-base-ubuntu20.04
    runtime: "runc"
    user: ${CURRENT_UID}
    volumes:
      - /home/hskim/Projects/:/Projects
      - /srv/vital_amc:/srv/vital_amc
      - /srv/project_data:/srv/project_data
      - /srv/project_code:/srv/project_code
    ports:
      - "8891:8891"
      - "5006:5006"
    tty: true
    environment:
      - NVIDIA_VISIBLE_DEVICES=0 # which gpu do you want to use for this container
      - JUPYTER_TOKEN=signalserver
    entrypoint: ["/bin/bash","-c"]
    command:
      - |
        source activate dev-ml
        /bin/bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
